name: effitime
description: 高效时光 - 基于《高效能人士的七个习惯》理念的时间管理应用

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI 组件
  cupertino_icons: ^1.0.6
  material_color_utilities: ^0.8.0
  
  # 状态管理
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # 网络请求
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # 本地存储
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  
  # 导航
  go_router: ^12.1.3
  
  # 国际化
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  
  # 工具类
  uuid: ^4.2.1
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  
  # 日期时间
  timezone: ^0.9.2
  
  # 权限
  permission_handler: ^11.1.0
  
  # 设备信息
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  
  # 安全存储
  flutter_secure_storage: ^9.0.0
  
  # 图片处理
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  
  # 动画
  lottie: ^2.7.0
  
  # 图表
  fl_chart: ^0.66.0
  
  # 通知
  flutter_local_notifications: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # 代码生成
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  hive_generator: ^2.0.1
  
  # 代码检查
  flutter_lints: ^3.0.1
  
  # 图标生成
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # 国际化
  generate: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"